### ISSUE TITLE
Query parameters does not work

### ISSUE THREAD

**Issue by jardila** [carltongibson/azure-functions-wsgi-adapter#2]
Hello, i have a django application and it works very well, but when i try to send any request with query parameters the request does not receive any parameter.
Anyone knows any solution to fix this?

Here an example:
my request is: http://localhost:8000/index?name="Max"

In the code:

```
def index(request):

    return HttpResponse(request.GET)
```

The result is an empty response

**Comment by carltongibson** [comment]
Hi. 

We’d need to add mapping of the query string in request.py. 

Currently there are a few parts of the WSGI spec that aren’t mapped, but that would be a good first PR.

**Comment by jardila** [comment]
Thanks for answer me. i had to download the project in order to make some changes in it.
My solution was add a line with the request original value in request.py as you are saying.

My request.py is actually like this:

```
        environ.update({
            "REQUEST_METHOD": req.method,
            "wsgi.input": req.get_body(),  # Wrap in io.BytesIO?
            "SERVER_NAME": "localhost",
            "SERVER_PORT": "7071",
            "PATH_INFO": path_info,
            "REQUEST_ORIGIN": req
        })
```

Then, to receive that request in my endpoint i must to use this line:

```
req = request._request.environ["REQUEST_ORIGIN"]

```
I hope this solution would be useful for someone else.
